name: pull and merge changes from ${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }} branch
on:
  push:
    branches:
      - ${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }}

jobs:
  pull_and_merge_changes_from_testing_into_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pull_request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          commit-message: "Merge testing into main"
          title: "Merge ${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }} into main"
          body: "This pull request merges changes from the testing branch into the main branch."
          labels: "automerge"