name: Merge Pull Request from main to deploy/testing

on:
  push:
    branches:
      - main

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Pull Request
        id: merge_pull_request
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          BASE_URL="https://api.github.com"
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.repository }}"
          SOURCE_BRANCH="main"
          TARGET_BRANCH="deploy/testing"

          # Get Pull Request Number
          PR_NUMBER=$(curl -s "$BASE_URL/repos/$OWNER/$REPO/pulls?state=closed&base=$TARGET_BRANCH&head=$OWNER:$SOURCE_BRANCH" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" | jq -r '.[0].number')

          if [[ -n "$PR_NUMBER" ]]; then
            # Merge Pull Request
            curl -X PUT "$BASE_URL/repos/$OWNER/$REPO/pulls/$PR_NUMBER/merge" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{
                "commit_title": "Merge pull request #'$PR_NUMBER'",
                "commit_message": "Auto-merge pull request #'$PR_NUMBER'",
                "merge_method": "merge"
              }'
          else
            echo "No Pull Request found"
          fi

      - name: Pull Changes from deploy/testing to main
        if: steps.merge_pull_request.outputs.result == 'merged'
        run: |
          git fetch origin
          git checkout -b deploy-testing origin/deploy/testing
          git merge --no-ff --no-commit origin/deploy/testing
          # Additional steps to handle the merged changes

          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -m "Merge changes from deploy/testing to main"
          git push origin main
