name: Create and Merge Pull Request
on:
  push:
    branches:
      - main

jobs:
  create_and_merge_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Create Pull Request
        id: create_pull_request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }}
          commit-message: "Merge main into ${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }}"
          title: "Merge main into ${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }}"
          body: "This pull request merges changes from the main branch into the ${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }} branch."
          labels: "automerge"

      - name: Merge Pull Request
        uses: actions/github-script@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({
              auth: process.env.GITHUB_TOKEN
            });
            const prNumber = "${{ steps.create_pull_request.outputs.pull-request-number }}";
            octokit.pulls.merge({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.repository }}",
              pull_number: prNumber
            });
