name: Create Production Pull Request
on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create PR from ${{ github.ref_name }} into ${{ vars.PROPERTY_MANAGEMENT_MODULE_PRODUCTION_BRANCH }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: ./.github/actions/create-pr
        with:
          SOURCE_BRANCH: ${{ github.ref_name }}
          DESTINATION_BRANCH: ${{ vars.PROPERTY_MANAGEMENT_MODULE_PRODUCTION_BRANCH }}
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}

      - name: log it
        run: |
          echo "output - created PR: $PR_NUMBER"