name: Create and Merge Pull Request
on:
  push:
    branches:
      - main

jobs:
  create_and_merge_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        id: create_pull_request
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          BASE_URL="https://api.github.com"
          REPO="${{ github.repository }}"
          BRANCH="${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }}"
          SOURCE_BRANCH="${{ github.ref_name }}"
          echo "SOURCE_BRANCH: $SOURCE_BRANCH"
          echo "BRANCH: $BRANCH"

          # Create Pull Request
          PR_RESPONSE=$(curl -X POST "$BASE_URL/repos/$REPO/pulls" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "title": "Merge main into ${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }}",
              "head": "$SOURCE_BRANCH",
              "base": "'"$BRANCH"'"
            }')

          # Extract Pull Request Number
          PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')

          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

          echo "Created Pull Request #$PR_NUMBER"

      - name: Merge Pull Request to ${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: merge_pull_request
        run: |
          BASE_URL="https://api.github.com"
          REPO="${{ github.repository }}"
          
          PR_NUMBER="$PR_NUMBER"

          echo "steps.create_pull_request.outputs.pr_number: $PR_NUMBER"

          url="$BASE_URL/repos/$REPO/pulls/$PR_NUMBER/merge"
          echo "$url"

          # Merge Pull Request
          curl -L -X PUT $url \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "commit_title": "Merge pull request #$PR_NUMBER",
              "commit_message": "Auto-merge pull request #$PR_NUMBER"
            }'
