name: Create and Merge Pull Request
on:
  push:
    branches:
      - main

jobs:
  create_and_merge_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create PR from ${{ github.ref_name }} into ${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: ./.github/actions/create_pr
        with:
          SOURCE_BRANCH: ${{ github.ref_name }}
          DESTINATION_BRANCH: ${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }}
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}

      - name: log it
        run: |
          echo "output - created PR: $PR_NUMBER"

      - name: Merge Pull Request to ${{ vars.PROPERTY_MANAGEMENT_MODULE_TESTING_BRANCH }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: merge_pull_request
        run: |
          BASE_URL="https://api.github.com"
          REPO="${{ github.repository }}"
          
          PR_NUMBER="$PR_NUMBER"

          echo "steps.create_pull_request.outputs.pr_number: $PR_NUMBER"

          url="$BASE_URL/repos/$REPO/pulls/$PR_NUMBER/merge"
          echo "$url"

          # Merge Pull Request
          curl -L -X PUT $url \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "commit_title": "Merge pull request #$PR_NUMBER",
              "commit_message": "Auto-merge pull request #$PR_NUMBER"
            }'
