name: Create and Merge Pull Request
on:
  push:
    branches:
      - main

jobs:
  create_and_merge_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Create Pull Request
        id: create_pull_request
        run: |
          BASE_URL="https://api.github.com"
          OWNER="saru2020"
          REPO="clickup_GHA_poc"
          BRANCH="deploy/testing"

          # Create Pull Request
          PR_RESPONSE=$(curl -X POST "$BASE_URL/repos/$OWNER/$REPO/pulls" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "title": "Merge main into deploy/testing",
              "head": "main",
              "base": "'"$BRANCH"'"
            }')

          # Extract Pull Request Number
          PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')

          echo "::set-output name=pr_number::$PR_NUMBER"
          echo "Created Pull Request #$PR_NUMBER"

      - name: Merge Pull Request to deploy/testing
        id: merge_pull_request
        run: |
          git fetch origin deploy/testing:deploy/testing
          git merge deploy/testing --no-commit --no-ff

          BASE_URL="https://api.github.com"
          OWNER="saru2020"
          REPO="clickup_GHA_poc"
          # BRANCH="deploy/testing"
          
          PR_NUMBER=${{ steps.create_pull_request.outputs.pr_number }}

          echo "steps.create_pull_request.outputs.pr_number: $PR_NUMBER"

          url="$BASE_URL/repos/$OWNER/$REPO/pulls/$PR_NUMBER/merge"
          echo "$url"

          # Merge Pull Request
          curl -L -X PUT $url \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "commit_title": "Merge pull request #$PR_NUMBER",
              "commit_message": "Auto-merge pull request #$PR_NUMBER"
            }'
