name: Create and Merge Pull Request
on:
  push:
    branches:
      - main

jobs:
  create_and_merge_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        id: create_pull_request
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          BASE_URL="https://api.github.com"
          OWNER="saru2020"
          REPO="clickup_GHA_poc"
          BRANCH="deploy/testing"

          # Create Pull Request
          PR_RESPONSE=$(curl -X POST "$BASE_URL/repos/$OWNER/$REPO/pulls" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "title": "Merge main into deploy/testing",
              "head": "main",
              "base": "'"$BRANCH"'"
            }')

          # Extract Pull Request Number
          PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')

          # echo "::set-output name=pr_number::$PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

          echo "Created Pull Request #$PR_NUMBER"

      - name: Merge Pull Request to deploy/testing
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: merge_pull_request
        run: |
          BASE_URL="https://api.github.com"
          OWNER="saru2020"
          REPO="clickup_GHA_poc"
          # BRANCH="deploy/testing"
          
          # PR_NUMBER=${{ steps.create_pull_request.outputs.pr_number }}
          PR_NUMBER="$PR_NUMBER"

          echo "steps.create_pull_request.outputs.pr_number: $PR_NUMBER"

          url="$BASE_URL/repos/$OWNER/$REPO/pulls/$PR_NUMBER/merge"
          echo "$url"

          # Merge Pull Request
          curl -L -X PUT $url \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "commit_title": "Merge pull request #$PR_NUMBER",
              "commit_message": "Auto-merge pull request #$PR_NUMBER"
            }'

      - name: wait
        uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '5' # for 5 seconds

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
                  
      - name: Pull Changes from deploy/testing to main
        id: pull_changes_from_testing_into_main
        # if: steps.merge_pull_request.outputs.result == 'merged'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin
          git pull --no-ff --no-commit origin deploy/testing
          git status
          git push origin main