name: Create Pull Request
on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pull_request
        uses: repo-sync/pull-request@v2
        with:
          destinationBranch: deploy/testing
          sourceBranch: main
          title: "Merge main into deploy/testing"
          body: "This pull request merges changes from the main branch into the deploy/testing branch.."
