name: Do Something That Needs Scheduled

on:
  repository_dispatch:
    types: do-something

jobs:
  merge_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge main into testing
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout testing
          git merge main
          git push origin testing
