name: Merge from main to testing

on:
  repository_dispatch:
    types: merge-main-to-testing

jobs:
  merge_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge development -> testing
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: testing
          github_token: ${{ secrets.GITHUB_TOKEN }}
