name: Update DynamoDB on Schema Changes

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  updateDynamoDB:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install ts-node
      run: npm -g install ts-node

    - name: Create temporary directories
      run: |
        mkdir -p temp_source
        mkdir -p temp_destination

    - name: Fetch base branch
      run: git fetch origin ${{ github.event.pull_request.base.ref }}

    - name: Checkout base branch
      run: git --work-tree=temp_destination checkout FETCH_HEAD

    - name: Copy schema from base branch
      run: cp amplify/schema.graphql temp_destination/destination_schema.graphql

    - name: Fetch source branch
      run: git fetch origin ${{ github.event.pull_request.head.ref }}

    - name: Checkout source branch
      run: git --work-tree=temp_source checkout FETCH_HEAD

    - name: Copy schema from source branch
      run: cp amplify/schema.graphql temp_source/source_schema.graphql

    - name: Print temporary directories
      run: |
        echo "ls"
        ls
        echo "ls -a"
        ls -a
        echo "temp_destination"
        ls temp_destination
        echo "temp_source"
        ls temp_source

    - name: Find Removed Fields
      run: |
        ts-node tools/find-removed-fields.ts temp_destination/destination_schema.graphql temp_source/source_schema.graphql

    - name: Clean up temporary directories
      run: |
        rm -rf temp_source
        rm -rf temp_destination
