name: Update DynamoDB on Schema Changes

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  updateDynamoDB:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install ts-node
      run: npm -g install ts-node

    - name: Fetch source branch
      run: git fetch origin ${{ github.event.pull_request.head.ref }}

    - name: Checkout source branch
      run: git checkout FETCH_HEAD

    - name: Copy schema from source branch
      run: cp amplify/schema.graphql source_schema.graphql

    - name: Fetch base branch
      run: git fetch origin ${{ github.event.pull_request.base.ref }}

    - name: Checkout base branch
      run: git checkout FETCH_HEAD

    - name: Copy schema from base branch
      run: cp amplify/schema.graphql destination_schema.graphql

    - name: Find Removed Fields
      run: |
        ts-node 'tools/find-removed-fields' source_schema.graphql destination_schema.graphql
