name: Update DynamoDB on Schema Changes

on:
  pull_request:
    types:
      - closed
# on:
#   pull_request:
#     types:
#       - opened
#       - synchronize

jobs:
  updateDynamoDB:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    # - name: Install ts-node
    #   run: npm -g install ts-node

    - name: Create temporary directories
      run: |
        mkdir -p temp_destination

    # - name: Fetch base branch
    #   run: git fetch origin ${{ github.event.pull_request.base.ref }}

    - name: Fetch previous commit
      run: git fetch origin ${{ github.event.pull_request.base.ref }}
      
    # - name: Checkout base branch
    #   run: git --work-tree=temp_destination checkout FETCH_HEAD

    # - name: Find Removed Fields
    #   run: node tools/removed_fields/datamanager/handle_removed_fields.js temp_destination/amplify/schema.graphql amplify/schema.graphql

    # not working
    # - name: Checkout to previous commit
    #   run: git --work-tree=temp_destination checkout $(git rev-parse FETCH_HEAD^1)

    # not working
    # - name: Checkout the previous commit
    #   run: git checkout HEAD^
    #   working-directory: temp_destination


    - name: Get the SHA of the previous commit
      id: prev_commit
      run: echo "::set-output name=sha::$(git rev-parse ${{ github.sha }}^1)"

    - name: Checkout the previous commit
      run: git checkout ${{ steps.prev_commit.outputs.sha }}
      working-directory: temp_destination
      
    - name: Find Removed Fields
      run: node tools/removed_fields/datamanager/handle_removed_fields.js amplify/schema.graphql temp_destination/amplify/schema.graphql

    - name: Clean up temporary directories
      run: |
        rm -rf temp_destination
