name: Update DynamoDB on Schema Changes

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  updateDynamoDB:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install ts-node
      run: npm -g install ts-node

    - name: Create temporary directories
      run: |
        mkdir -p temp_destination

    - name: Fetch base branch
      run: git fetch origin ${{ github.event.pull_request.base.ref }}

    - name: Checkout base branch
      run: git --work-tree=temp_destination checkout FETCH_HEAD

    - name: Find Removed Fields
      run: ts-node tools/find-removed-fields.ts temp_destination/amplify/schema.graphql amplify/schema.graphql

    - name: Clean up temporary directories
      run: |
        rm -rf temp_destination
